name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test Utils
        run: go test -v ./utils/...

      - name: Build CLI
        run: ./build.sh

      - name: Build GUI
        run: ./build.sh --with-gui
